# Auto-generated training data for spaCy NER model

TRAIN_DATA = [('My name is Kamal Perera and I live in Nuwara Eliya.',
  {'entities': [(11, 23, 'PERSON'), (38, 50, 'LOCATION')]}),
 ('The report was sent by an Engineer from Kandy.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 45, 'LOCATION')]}),
 ('The main office is located in Galle.', {'entities': [(30, 35, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The main office is located in Ratnapura.',
  {'entities': [(30, 39, 'LOCATION')]}),
 ('The report was sent by an CEO from Negombo.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 42, 'LOCATION')]}),
 ('I saw Niluka yesterday.', {'entities': [(6, 12, 'PERSON')]}),
 ('Please contact Ruwan on his number +94768028324.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('You can reach the Director at +94770125518.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('My name is Geetha and I live in Galle.',
  {'entities': [(11, 17, 'PERSON'), (32, 37, 'LOCATION')]}),
 ('Her NIC is 192246115098 and she is a Supervisor.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 47, 'JOB_TITLE')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 558153774V and she is a Engineer.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('Her NIC is 200645382307 and she is a Engineer.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('You can reach the Supervisor at +94711240957.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ("Niluka's ID number is 190817820759.",
  {'entities': [(0, 6, 'PERSON'), (22, 34, 'SL_NIC')]}),
 ('The main office is located in Matara.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('The report was sent by an Engineer from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 62, 'LOCATION')]}),
 ('You can reach the Manager at +94764881371.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('Please contact Anusha Silva on his number +94757103884.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Supervisor from Kandy.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 47, 'LOCATION')]}),
 ('Please contact Karthik on his number +94769187369.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('I saw Suresh Pillai yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('You can reach the Engineer at +94715538985.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Supervisor at +94758879842.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ("Kamal Perera's ID number is 194610442448.",
  {'entities': [(0, 12, 'PERSON'), (28, 40, 'SL_NIC')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Please contact Suresh Pillai on his number +94716298777.',
  {'entities': [(15, 28, 'PERSON'), (43, 55, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 198764496579 and she is a CEO.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 40, 'JOB_TITLE')]}),
 ("Priya Subramaniam's ID number is 637409208V.",
  {'entities': [(0, 17, 'PERSON'), (33, 43, 'SL_NIC')]}),
 ('Please contact Sunil Fernando on his number +94741029192.',
  {'entities': [(15, 29, 'PERSON'), (44, 56, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Engineer from Kandy.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 45, 'LOCATION')]}),
 ('My name is Chamara and I live in Galle.',
  {'entities': [(11, 18, 'PERSON'), (33, 38, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the Director at +94726782286.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 575321563V and she is a Supervisor.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 45, 'JOB_TITLE')]}),
 ('The report was sent by an Director from Anuradhapura.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 52, 'LOCATION')]}),
 ('You can reach the Supervisor at +94776963869.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Director at +94711032125.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('My name is Mahela Jayawardena and I live in Jaffna.',
  {'entities': [(11, 29, 'PERSON'), (44, 50, 'LOCATION')]}),
 ('My name is Suresh Pillai and I live in Trincomalee.',
  {'entities': [(11, 24, 'PERSON'), (39, 50, 'LOCATION')]}),
 ('Please contact Deepika on his number +94769494397.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ("Priya Subramaniam's ID number is 169747985V.",
  {'entities': [(0, 17, 'PERSON'), (33, 43, 'SL_NIC')]}),
 ("Gayan Bandara's ID number is 192539287036.",
  {'entities': [(0, 13, 'PERSON'), (29, 41, 'SL_NIC')]}),
 ('My name is Geetha and I live in Dehiwala-Mount Lavinia.',
  {'entities': [(11, 17, 'PERSON'), (32, 54, 'LOCATION')]}),
 ('You can reach the Director at +94758451086.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 190786436114 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Please contact Karthik on his number +94796298938.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Director at +94752529086.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Kandy.', {'entities': [(30, 35, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('I saw Deepika yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('My name is Geetha and I live in Kandy.',
  {'entities': [(11, 17, 'PERSON'), (32, 37, 'LOCATION')]}),
 ('The report was sent by an Supervisor from Matara.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 48, 'LOCATION')]}),
 ('Her NIC is 910219763V and she is a Director.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('I saw Mahinda Rajapaksa yesterday.', {'entities': [(6, 23, 'PERSON')]}),
 ('Her NIC is 392804153V and she is a Manager.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 42, 'JOB_TITLE')]}),
 ('I saw Sunil Fernando yesterday.', {'entities': [(6, 20, 'PERSON')]}),
 ('You can reach the Manager at +94756179614.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Manager at +94740938721.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ("Karthik's ID number is 196958752546.",
  {'entities': [(0, 7, 'PERSON'), (23, 35, 'SL_NIC')]}),
 ('Her NIC is 201891276478 and she is a Manager.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 44, 'JOB_TITLE')]}),
 ('My name is Deepika and I live in Trincomalee.',
  {'entities': [(11, 18, 'PERSON'), (33, 44, 'LOCATION')]}),
 ('You can reach the Engineer at +94780190153.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Negombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('The main office is located in Jaffna.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('Her NIC is 188257944V and she is a CEO.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 38, 'JOB_TITLE')]}),
 ('Her NIC is 191815166341 and she is a Supervisor.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 47, 'JOB_TITLE')]}),
 ('My name is Sunil Fernando and I live in Trincomalee.',
  {'entities': [(11, 25, 'PERSON'), (40, 51, 'LOCATION')]}),
 ("Ruwan's ID number is 198413450117.",
  {'entities': [(0, 5, 'PERSON'), (21, 33, 'SL_NIC')]}),
 ('Please contact Priya Subramaniam on his number +94730562883.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('You can reach the Manager at +94765600975.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Engineer at +94763985465.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Supervisor at +94765110547.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('Please contact Chamara on his number +94756634337.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 202014381389 and she is a CEO.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 40, 'JOB_TITLE')]}),
 ('I saw Geetha yesterday.', {'entities': [(6, 12, 'PERSON')]}),
 ('Her NIC is 190967606089 and she is a CEO.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 40, 'JOB_TITLE')]}),
 ('The report was sent by an Supervisor from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 64, 'LOCATION')]}),
 ('You can reach the Director at +94771526494.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ("Karthik's ID number is 739932595V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('You can reach the CEO at +94739153484.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('My name is Karthik and I live in Kandy.',
  {'entities': [(11, 18, 'PERSON'), (33, 38, 'LOCATION')]}),
 ('The main office is located in Kandy.', {'entities': [(30, 35, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 194647058192 and she is a Engineer.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an CEO from Kandy.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 40, 'LOCATION')]}),
 ('My name is Nimal and I live in Ratnapura.',
  {'entities': [(11, 16, 'PERSON'), (31, 40, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Priya Subramaniam's ID number is 600621350V.",
  {'entities': [(0, 17, 'PERSON'), (33, 43, 'SL_NIC')]}),
 ('The report was sent by an Engineer from Galle.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 45, 'LOCATION')]}),
 ('You can reach the Manager at +94799456394.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ("Mahinda Rajapaksa's ID number is 796143850V.",
  {'entities': [(0, 17, 'PERSON'), (33, 43, 'SL_NIC')]}),
 ('You can reach the Manager at +94786650628.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Mahela Jayawardena's ID number is 118974950V.",
  {'entities': [(0, 18, 'PERSON'), (34, 44, 'SL_NIC')]}),
 ('My name is Niluka and I live in Matara.',
  {'entities': [(11, 17, 'PERSON'), (32, 38, 'LOCATION')]}),
 ('My name is Priya Subramaniam and I live in Anuradhapura.',
  {'entities': [(11, 28, 'PERSON'), (43, 55, 'LOCATION')]}),
 ('I saw Anusha Silva yesterday.', {'entities': [(6, 18, 'PERSON')]}),
 ('Please contact Mahinda Rajapaksa on his number +94760783575.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Engineer from Nuwara Eliya.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 52, 'LOCATION')]}),
 ('Her NIC is 201527000334 and she is a Supervisor.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 47, 'JOB_TITLE')]}),
 ('The report was sent by an CEO from Anuradhapura.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 47, 'LOCATION')]}),
 ('You can reach the Engineer at +94749875168.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The main office is located in Anuradhapura.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ("Gayan Bandara's ID number is 550265538V.",
  {'entities': [(0, 13, 'PERSON'), (29, 39, 'SL_NIC')]}),
 ('My name is Priya Subramaniam and I live in Dehiwala-Mount Lavinia.',
  {'entities': [(11, 28, 'PERSON'), (43, 65, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Her NIC is 191319378155 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Negombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('Please contact Arun Kumar on his number +94774884046.',
  {'entities': [(15, 25, 'PERSON'), (40, 52, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an CEO from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 57, 'LOCATION')]}),
 ('I saw Suresh Pillai yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('You can reach the Manager at +94779311160.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the Director at +94772976631.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('My name is Arun Kumar and I live in Anuradhapura.',
  {'entities': [(11, 21, 'PERSON'), (36, 48, 'LOCATION')]}),
 ('The main office is located in Moratuwa.',
  {'entities': [(30, 38, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ("Lasantha's ID number is 711650895V.",
  {'entities': [(0, 8, 'PERSON'), (24, 34, 'SL_NIC')]}),
 ('Her NIC is 190432107101 and she is a CEO.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 40, 'JOB_TITLE')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The main office is located in Kandy.', {'entities': [(30, 35, 'LOCATION')]}),
 ('The main office is located in Ratnapura.',
  {'entities': [(30, 39, 'LOCATION')]}),
 ('My name is Geetha and I live in Colombo.',
  {'entities': [(11, 17, 'PERSON'), (32, 39, 'LOCATION')]}),
 ("Kamal Perera's ID number is 198573098265.",
  {'entities': [(0, 12, 'PERSON'), (28, 40, 'SL_NIC')]}),
 ('I saw Kamal Perera yesterday.', {'entities': [(6, 18, 'PERSON')]}),
 ('My name is Suresh Pillai and I live in Colombo.',
  {'entities': [(11, 24, 'PERSON'), (39, 46, 'LOCATION')]}),
 ('The report was sent by an Supervisor from Galle.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 47, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the CEO at +94796637314.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('I saw Nimal yesterday.', {'entities': [(6, 11, 'PERSON')]}),
 ('You can reach the Manager at +94795530896.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('My name is Karthik and I live in Moratuwa.',
  {'entities': [(11, 18, 'PERSON'), (33, 41, 'LOCATION')]}),
 ('The main office is located in Negombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('My name is Mahela Jayawardena and I live in Dehiwala-Mount Lavinia.',
  {'entities': [(11, 29, 'PERSON'), (44, 66, 'LOCATION')]}),
 ('The main office is located in Jaffna.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('Please contact Mahinda Rajapaksa on his number +94783650997.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Supervisor at +94744070991.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Director at +94722342289.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 196829333003 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ("Sunil Fernando's ID number is 194389507251.",
  {'entities': [(0, 14, 'PERSON'), (30, 42, 'SL_NIC')]}),
 ('The main office is located in Nuwara Eliya.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('The report was sent by an Engineer from Matara.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 46, 'LOCATION')]}),
 ('Please contact Gayan Bandara on his number +94790766139.',
  {'entities': [(15, 28, 'PERSON'), (43, 55, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 106154931V and she is a Engineer.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 197158910131 and she is a Supervisor.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 47, 'JOB_TITLE')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('My name is Sunil Fernando and I live in Jaffna.',
  {'entities': [(11, 25, 'PERSON'), (40, 46, 'LOCATION')]}),
 ('Please contact Anusha Silva on his number +94789234669.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Manager at +94777561630.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please contact Niluka on his number +94787896362.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ("Mahela Jayawardena's ID number is 195656232750.",
  {'entities': [(0, 18, 'PERSON'), (34, 46, 'SL_NIC')]}),
 ('You can reach the CEO at +94729657879.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Supervisor from Kandy.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 47, 'LOCATION')]}),
 ('The main office is located in Trincomalee.',
  {'entities': [(30, 41, 'LOCATION')]}),
 ('The report was sent by an Supervisor from Anuradhapura.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 54, 'LOCATION')]}),
 ('My name is Kamal Perera and I live in Kandy.',
  {'entities': [(11, 23, 'PERSON'), (38, 43, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('I saw Mahela Jayawardena yesterday.', {'entities': [(6, 24, 'PERSON')]}),
 ('The main office is located in Nuwara Eliya.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('Her NIC is 197065086532 and she is a Manager.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 44, 'JOB_TITLE')]}),
 ('The report was sent by an Engineer from Moratuwa.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 48, 'LOCATION')]}),
 ('My name is Lasantha and I live in Kandy.',
  {'entities': [(11, 19, 'PERSON'), (34, 39, 'LOCATION')]}),
 ('I saw Arun Kumar yesterday.', {'entities': [(6, 16, 'PERSON')]}),
 ('I saw Priya Subramaniam yesterday.', {'entities': [(6, 23, 'PERSON')]}),
 ('Please contact Anusha Silva on his number +94776768738.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Trincomalee.',
  {'entities': [(30, 41, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ("Chamara's ID number is 213668276V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Sunil Fernando's ID number is 459437578V.",
  {'entities': [(0, 14, 'PERSON'), (30, 40, 'SL_NIC')]}),
 ('You can reach the Supervisor at +94743637775.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Engineer at +94721875730.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Supervisor at +94787143671.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('Please contact Priya Subramaniam on his number +94711704487.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ("Lasantha's ID number is 197897784536.",
  {'entities': [(0, 8, 'PERSON'), (24, 36, 'SL_NIC')]}),
 ('You can reach the Supervisor at +94731595777.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Please contact Mahela Jayawardena on his number +94751738965.',
  {'entities': [(15, 33, 'PERSON'), (48, 60, 'SL_PHONE_NUMBER')]}),
 ("Deepika's ID number is 810708794V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ("Suresh Pillai's ID number is 197462192433.",
  {'entities': [(0, 13, 'PERSON'), (29, 41, 'SL_NIC')]}),
 ('The report was sent by an Manager from Matara.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 45, 'LOCATION')]}),
 ('The main office is located in Colombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ("Anusha Silva's ID number is 195595106254.",
  {'entities': [(0, 12, 'PERSON'), (28, 40, 'SL_NIC')]}),
 ('The main office is located in Colombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('My name is Geetha and I live in Trincomalee.',
  {'entities': [(11, 17, 'PERSON'), (32, 43, 'LOCATION')]}),
 ('Please contact Niluka on his number +94764210260.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 190274242361 and she is a Manager.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 44, 'JOB_TITLE')]}),
 ("Geetha's ID number is 541662491V.",
  {'entities': [(0, 6, 'PERSON'), (22, 32, 'SL_NIC')]}),
 ('Please contact Chamara on his number +94738759176.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('I saw Lasantha yesterday.', {'entities': [(6, 14, 'PERSON')]}),
 ('I saw Suresh Pillai yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('My name is Kamal Perera and I live in Ratnapura.',
  {'entities': [(11, 23, 'PERSON'), (38, 47, 'LOCATION')]}),
 ('The report was sent by an Engineer from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 62, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please contact Karthik on his number +94744778394.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the Manager at +94741749389.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('Please contact Priya Subramaniam on his number +94755789370.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Matara.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('The main office is located in Colombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('The main office is located in Trincomalee.',
  {'entities': [(30, 41, 'LOCATION')]}),
 ('The report was sent by an Supervisor from Negombo.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 49, 'LOCATION')]}),
 ('You can reach the CEO at +94779050386.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ("Chamara's ID number is 382458948V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('I saw Mahela Jayawardena yesterday.', {'entities': [(6, 24, 'PERSON')]}),
 ('The main office is located in Kandy.', {'entities': [(30, 35, 'LOCATION')]}),
 ('You can reach the Director at +94790355378.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 190238248931 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('The report was sent by an Director from Negombo.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 47, 'LOCATION')]}),
 ('You can reach the CEO at +94735468047.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 199035820209 and she is a Engineer.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('The main office is located in Nuwara Eliya.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('Please contact Ruwan on his number +94750304987.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Chamara's ID number is 201530160V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('Her NIC is 191726883919 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Her NIC is 298112509V and she is a CEO.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 38, 'JOB_TITLE')]}),
 ('Her NIC is 200953330385 and she is a Supervisor.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 47, 'JOB_TITLE')]}),
 ('The main office is located in Matara.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('I saw Suresh Pillai yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('Please contact Niluka on his number +94764579798.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ("Lasantha's ID number is 192511674829.",
  {'entities': [(0, 8, 'PERSON'), (24, 36, 'SL_NIC')]}),
 ('The report was sent by an Supervisor from Nuwara Eliya.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 54, 'LOCATION')]}),
 ('The report was sent by an CEO from Kandy.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 40, 'LOCATION')]}),
 ('You can reach the Supervisor at +94779145039.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 195984576172 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Please contact Geetha on his number +94764961569.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ('I saw Chamara yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Sunil Fernando's ID number is 197494952463.",
  {'entities': [(0, 14, 'PERSON'), (30, 42, 'SL_NIC')]}),
 ('My name is Karthik and I live in Colombo.',
  {'entities': [(11, 18, 'PERSON'), (33, 40, 'LOCATION')]}),
 ('Please contact Chamara on his number +94746049087.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('You can reach the CEO at +94788973705.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ("Karthik's ID number is 344134858V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The main office is located in Jaffna.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the Director at +94749941709.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Her NIC is 621408170V and she is a Engineer.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('My name is Mahinda Rajapaksa and I live in Galle.',
  {'entities': [(11, 28, 'PERSON'), (43, 48, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Her NIC is 194248415302 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 197799860001 and she is a Supervisor.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 47, 'JOB_TITLE')]}),
 ('Please contact Niluka on his number +94758295003.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ("Mahela Jayawardena's ID number is 195917028306.",
  {'entities': [(0, 18, 'PERSON'), (34, 46, 'SL_NIC')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The main office is located in Trincomalee.',
  {'entities': [(30, 41, 'LOCATION')]}),
 ('You can reach the Director at +94721753053.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Manager at +94799181780.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Supervisor from Kandy.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 47, 'LOCATION')]}),
 ('I saw Kamal Perera yesterday.', {'entities': [(6, 18, 'PERSON')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('My name is Mahinda Rajapaksa and I live in Colombo.',
  {'entities': [(11, 28, 'PERSON'), (43, 50, 'LOCATION')]}),
 ("Geetha's ID number is 279269744V.",
  {'entities': [(0, 6, 'PERSON'), (22, 32, 'SL_NIC')]}),
 ('The report was sent by an CEO from Colombo.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 42, 'LOCATION')]}),
 ('Her NIC is 199080780082 and she is a CEO.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 40, 'JOB_TITLE')]}),
 ('The report was sent by an CEO from Negombo.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 42, 'LOCATION')]}),
 ('Her NIC is 192380771702 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Dehiwala-Mount Lavinia.',
  {'entities': [(30, 52, 'LOCATION')]}),
 ('The main office is located in Matara.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('Please contact Niluka on his number +94784016484.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Nuwara Eliya.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('You can reach the Engineer at +94726015793.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 609841619V and she is a Manager.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 42, 'JOB_TITLE')]}),
 ("Arun Kumar's ID number is 889460892V.",
  {'entities': [(0, 10, 'PERSON'), (26, 36, 'SL_NIC')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The report was sent by an Engineer from Anuradhapura.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 52, 'LOCATION')]}),
 ('I saw Arun Kumar yesterday.', {'entities': [(6, 16, 'PERSON')]}),
 ('I saw Deepika yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Her NIC is 464122201V and she is a Supervisor.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 45, 'JOB_TITLE')]}),
 ('The main office is located in Anuradhapura.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Manager from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 61, 'LOCATION')]}),
 ('I saw Chamara yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('Please contact Ruwan on his number +94777433426.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Director at +94766272784.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The main office is located in Jaffna.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('You can reach the Supervisor at +94744482637.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Ratnapura.',
  {'entities': [(30, 39, 'LOCATION')]}),
 ('Please contact Deepika on his number +94793810450.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Anusha Silva's ID number is 244178428V.",
  {'entities': [(0, 12, 'PERSON'), (28, 38, 'SL_NIC')]}),
 ('My name is Arun Kumar and I live in Moratuwa.',
  {'entities': [(11, 21, 'PERSON'), (36, 44, 'LOCATION')]}),
 ('The main office is located in Trincomalee.',
  {'entities': [(30, 41, 'LOCATION')]}),
 ('Please contact Mahinda Rajapaksa on his number +94786830152.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('Please contact Gayan Bandara on his number +94791160078.',
  {'entities': [(15, 28, 'PERSON'), (43, 55, 'SL_PHONE_NUMBER')]}),
 ('My name is Geetha and I live in Anuradhapura.',
  {'entities': [(11, 17, 'PERSON'), (32, 44, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Kamal Perera's ID number is 458818354V.",
  {'entities': [(0, 12, 'PERSON'), (28, 38, 'SL_NIC')]}),
 ('Her NIC is 308334300V and she is a Manager.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 42, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Galle.', {'entities': [(30, 35, 'LOCATION')]}),
 ('The main office is located in Anuradhapura.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ("Geetha's ID number is 908869614V.",
  {'entities': [(0, 6, 'PERSON'), (22, 32, 'SL_NIC')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Manager from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 61, 'LOCATION')]}),
 ('You can reach the CEO at +94746216923.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ("Mahela Jayawardena's ID number is 971211385V.",
  {'entities': [(0, 18, 'PERSON'), (34, 44, 'SL_NIC')]}),
 ('I saw Niluka yesterday.', {'entities': [(6, 12, 'PERSON')]}),
 ('My name is Niluka and I live in Trincomalee.',
  {'entities': [(11, 17, 'PERSON'), (32, 43, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The report was sent by an Manager from Negombo.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 46, 'LOCATION')]}),
 ('I saw Kamal Perera yesterday.', {'entities': [(6, 18, 'PERSON')]}),
 ('Please contact Anusha Silva on his number +94751270726.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Supervisor from Negombo.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 49, 'LOCATION')]}),
 ('Please contact Suresh Pillai on his number +94723804098.',
  {'entities': [(15, 28, 'PERSON'), (43, 55, 'SL_PHONE_NUMBER')]}),
 ('Please contact Ruwan on his number +94751261741.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Engineer from Trincomalee.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 51, 'LOCATION')]}),
 ('Please contact Nimal on his number +94746766451.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Moratuwa.',
  {'entities': [(30, 38, 'LOCATION')]}),
 ('The main office is located in Anuradhapura.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('My name is Niluka and I live in Dehiwala-Mount Lavinia.',
  {'entities': [(11, 17, 'PERSON'), (32, 54, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('My name is Anusha Silva and I live in Negombo.',
  {'entities': [(11, 23, 'PERSON'), (38, 45, 'LOCATION')]}),
 ('I saw Ruwan yesterday.', {'entities': [(6, 11, 'PERSON')]}),
 ('I saw Deepika yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('Her NIC is 192549431635 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Her NIC is 985278614V and she is a Supervisor.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 45, 'JOB_TITLE')]}),
 ('The report was sent by an Engineer from Ratnapura.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 49, 'LOCATION')]}),
 ('Please contact Mahinda Rajapaksa on his number +94729768215.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Engineer from Matara.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 46, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('My name is Suresh Pillai and I live in Ratnapura.',
  {'entities': [(11, 24, 'PERSON'), (39, 48, 'LOCATION')]}),
 ('Please contact Anusha Silva on his number +94734483166.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('Please contact Mahela Jayawardena on his number +94719488123.',
  {'entities': [(15, 33, 'PERSON'), (48, 60, 'SL_PHONE_NUMBER')]}),
 ("Gayan Bandara's ID number is 879338331V.",
  {'entities': [(0, 13, 'PERSON'), (29, 39, 'SL_NIC')]}),
 ('Please contact Mahela Jayawardena on his number +94722941389.',
  {'entities': [(15, 33, 'PERSON'), (48, 60, 'SL_PHONE_NUMBER')]}),
 ('My name is Chamara and I live in Moratuwa.',
  {'entities': [(11, 18, 'PERSON'), (33, 41, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an CEO from Kandy.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 40, 'LOCATION')]}),
 ("Priya Subramaniam's ID number is 245659878V.",
  {'entities': [(0, 17, 'PERSON'), (33, 43, 'SL_NIC')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Her NIC is 905206052V and she is a CEO.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 38, 'JOB_TITLE')]}),
 ('I saw Chamara yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('I saw Gayan Bandara yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('The main office is located in Ratnapura.',
  {'entities': [(30, 39, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ("Niluka's ID number is 358406461V.",
  {'entities': [(0, 6, 'PERSON'), (22, 32, 'SL_NIC')]}),
 ('Please contact Anusha Silva on his number +94786052741.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('My name is Lasantha and I live in Ratnapura.',
  {'entities': [(11, 19, 'PERSON'), (34, 43, 'LOCATION')]}),
 ('Please contact Geetha on his number +94713598560.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Manager at +94747769700.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please contact Chamara on his number +94729772870.',
  {'entities': [(15, 22, 'PERSON'), (37, 49, 'SL_PHONE_NUMBER')]}),
 ('My name is Anusha Silva and I live in Matara.',
  {'entities': [(11, 23, 'PERSON'), (38, 44, 'LOCATION')]}),
 ('The main office is located in Dehiwala-Mount Lavinia.',
  {'entities': [(30, 52, 'LOCATION')]}),
 ("Niluka's ID number is 200574105627.",
  {'entities': [(0, 6, 'PERSON'), (22, 34, 'SL_NIC')]}),
 ('The report was sent by an Director from Nuwara Eliya.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 52, 'LOCATION')]}),
 ("Arun Kumar's ID number is 231269381V.",
  {'entities': [(0, 10, 'PERSON'), (26, 36, 'SL_NIC')]}),
 ('You can reach the Director at +94798845666.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('I saw Niluka yesterday.', {'entities': [(6, 12, 'PERSON')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the CEO at +94722529579.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Matara.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ("Arun Kumar's ID number is 192434316060.",
  {'entities': [(0, 10, 'PERSON'), (26, 38, 'SL_NIC')]}),
 ('The main office is located in Nuwara Eliya.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('The report was sent by an Manager from Jaffna.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 45, 'LOCATION')]}),
 ("Kamal Perera's ID number is 893710621V.",
  {'entities': [(0, 12, 'PERSON'), (28, 38, 'SL_NIC')]}),
 ('You can reach the Supervisor at +94787703999.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Supervisor from Dehiwala-Mount Lavinia.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 64, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('My name is Priya Subramaniam and I live in Ratnapura.',
  {'entities': [(11, 28, 'PERSON'), (43, 52, 'LOCATION')]}),
 ('Please contact Sunil Fernando on his number +94721181379.',
  {'entities': [(15, 29, 'PERSON'), (44, 56, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Director at +94748448025.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Please contact Nimal on his number +94746711988.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Supervisor from Galle.',
  {'entities': [(26, 36, 'JOB_TITLE'), (42, 47, 'LOCATION')]}),
 ('Please contact Gayan Bandara on his number +94724753519.',
  {'entities': [(15, 28, 'PERSON'), (43, 55, 'SL_PHONE_NUMBER')]}),
 ("Niluka's ID number is 541259793V.",
  {'entities': [(0, 6, 'PERSON'), (22, 32, 'SL_NIC')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Anuradhapura.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('Her NIC is 420333037V and she is a CEO.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 38, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Kandy.', {'entities': [(30, 35, 'LOCATION')]}),
 ('The report was sent by an CEO from Galle.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 40, 'LOCATION')]}),
 ('The main office is located in Kandy.', {'entities': [(30, 35, 'LOCATION')]}),
 ('Please contact Kamal Perera on his number +94752795841.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 168634418V and she is a Manager.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 42, 'JOB_TITLE')]}),
 ('Please contact Lasantha on his number +94795628684.',
  {'entities': [(15, 23, 'PERSON'), (38, 50, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Manager at +94749304059.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('My name is Suresh Pillai and I live in Ratnapura.',
  {'entities': [(11, 24, 'PERSON'), (39, 48, 'LOCATION')]}),
 ('Her NIC is 452982492V and she is a CEO.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 38, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('The main office is located in Matara.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ("Chamara's ID number is 989298678V.",
  {'entities': [(0, 7, 'PERSON'), (23, 33, 'SL_NIC')]}),
 ('The main office is located in Colombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('I saw Sunil Fernando yesterday.', {'entities': [(6, 20, 'PERSON')]}),
 ('The main office is located in Anuradhapura.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the CEO at +94755661430.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Please contact Mahela Jayawardena on his number +94776664849.',
  {'entities': [(15, 33, 'PERSON'), (48, 60, 'SL_PHONE_NUMBER')]}),
 ('My name is Mahinda Rajapaksa and I live in Galle.',
  {'entities': [(11, 28, 'PERSON'), (43, 48, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('You can reach the Manager at +94795215048.',
  {'entities': [(18, 25, 'JOB_TITLE'), (29, 41, 'SL_PHONE_NUMBER')]}),
 ('Please contact Kamal Perera on his number +94740676469.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ("Sunil Fernando's ID number is 537671911V.",
  {'entities': [(0, 14, 'PERSON'), (30, 40, 'SL_NIC')]}),
 ('Please contact Niluka on his number +94792765449.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('You can reach the Supervisor at +94786393215.',
  {'entities': [(18, 28, 'JOB_TITLE'), (32, 44, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Jaffna.',
  {'entities': [(30, 36, 'LOCATION')]}),
 ('I saw Gayan Bandara yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('The report was sent by an Director from Matara.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 46, 'LOCATION')]}),
 ('The main office is located in Nuwara Eliya.',
  {'entities': [(30, 42, 'LOCATION')]}),
 ('Her NIC is 200847654954 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]}),
 ('Please contact Gayan Bandara on his number +94758813954.',
  {'entities': [(15, 28, 'PERSON'), (43, 55, 'SL_PHONE_NUMBER')]}),
 ('My name is Niluka and I live in Kandy.',
  {'entities': [(11, 17, 'PERSON'), (32, 37, 'LOCATION')]}),
 ('I saw Gayan Bandara yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ("Suresh Pillai's ID number is 192920694984.",
  {'entities': [(0, 13, 'PERSON'), (29, 41, 'SL_NIC')]}),
 ('You can reach the Director at +94794990912.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Her NIC is 191655739256 and she is a Manager.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 44, 'JOB_TITLE')]}),
 ('I saw Ruwan yesterday.', {'entities': [(6, 11, 'PERSON')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('You can reach the CEO at +94758245693.',
  {'entities': [(18, 21, 'JOB_TITLE'), (25, 37, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Dehiwala-Mount Lavinia.',
  {'entities': [(30, 52, 'LOCATION')]}),
 ('I saw Arun Kumar yesterday.', {'entities': [(6, 16, 'PERSON')]}),
 ('My name is Niluka and I live in Galle.',
  {'entities': [(11, 17, 'PERSON'), (32, 37, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 526019095V and she is a Engineer.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('The report was sent by an Engineer from Nuwara Eliya.',
  {'entities': [(26, 34, 'JOB_TITLE'), (40, 52, 'LOCATION')]}),
 ('The main office is located in Negombo.',
  {'entities': [(30, 37, 'LOCATION')]}),
 ('Please contact Kamal Perera on his number +94793405194.',
  {'entities': [(15, 27, 'PERSON'), (42, 54, 'SL_PHONE_NUMBER')]}),
 ('I saw Suresh Pillai yesterday.', {'entities': [(6, 19, 'PERSON')]}),
 ('The report was sent by an CEO from Anuradhapura.',
  {'entities': [(26, 29, 'JOB_TITLE'), (35, 47, 'LOCATION')]}),
 ('Please contact Priya Subramaniam on his number +94769998157.',
  {'entities': [(15, 32, 'PERSON'), (47, 59, 'SL_PHONE_NUMBER')]}),
 ('I saw Ruwan yesterday.', {'entities': [(6, 11, 'PERSON')]}),
 ('You can reach the Engineer at +94756011864.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 811237035V and she is a Director.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('Her NIC is 838055561V and she is a Manager.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 42, 'JOB_TITLE')]}),
 ('I saw Priya Subramaniam yesterday.', {'entities': [(6, 23, 'PERSON')]}),
 ('You can reach the Director at +94736059645.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('I saw Nimal yesterday.', {'entities': [(6, 11, 'PERSON')]}),
 ('I saw Geetha yesterday.', {'entities': [(6, 12, 'PERSON')]}),
 ('I saw Mahinda Rajapaksa yesterday.', {'entities': [(6, 23, 'PERSON')]}),
 ('My name is Chamara and I live in Matara.',
  {'entities': [(11, 18, 'PERSON'), (33, 39, 'LOCATION')]}),
 ('Her NIC is 202172133761 and she is a CEO.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 40, 'JOB_TITLE')]}),
 ('Please contact Lasantha on his number +94713376025.',
  {'entities': [(15, 23, 'PERSON'), (38, 50, 'SL_PHONE_NUMBER')]}),
 ('You can reach the Director at +94781489041.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('The report was sent by an Manager from Moratuwa.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 47, 'LOCATION')]}),
 ('Please contact Arun Kumar on his number +94770439871.',
  {'entities': [(15, 25, 'PERSON'), (40, 52, 'SL_PHONE_NUMBER')]}),
 ('I saw Karthik yesterday.', {'entities': [(6, 13, 'PERSON')]}),
 ('Please contact Geetha on his number +94729578695.',
  {'entities': [(15, 21, 'PERSON'), (36, 48, 'SL_PHONE_NUMBER')]}),
 ('The report was sent by an Manager from Nuwara Eliya.',
  {'entities': [(26, 33, 'JOB_TITLE'), (39, 51, 'LOCATION')]}),
 ('Please contact Nimal on his number +94767930295.',
  {'entities': [(15, 20, 'PERSON'), (35, 47, 'SL_PHONE_NUMBER')]}),
 ('Her NIC is 147952471V and she is a CEO.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 38, 'JOB_TITLE')]}),
 ('There are no sensitive details in this message.', {'entities': []}),
 ('Please contact Sunil Fernando on his number +94711185174.',
  {'entities': [(15, 29, 'PERSON'), (44, 56, 'SL_PHONE_NUMBER')]}),
 ('My name is Suresh Pillai and I live in Kandy.',
  {'entities': [(11, 24, 'PERSON'), (39, 44, 'LOCATION')]}),
 ('Please review the attached quarterly report.', {'entities': []}),
 ('You can reach the Engineer at +94779831094.',
  {'entities': [(18, 26, 'JOB_TITLE'), (30, 42, 'SL_PHONE_NUMBER')]}),
 ('The main office is located in Trincomalee.',
  {'entities': [(30, 41, 'LOCATION')]}),
 ('Her NIC is 639581220V and she is a Engineer.',
  {'entities': [(11, 21, 'SL_NIC'), (35, 43, 'JOB_TITLE')]}),
 ('Her NIC is 193122248069 and she is a Director.',
  {'entities': [(11, 23, 'SL_NIC'), (37, 45, 'JOB_TITLE')]})]